import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'Privacy policy for Aernova Inc., including how quote request and contact form information is collected, used, shared, retained, and protected.',
  alternates: {
    canonical: '/privacy',
  },
  robots: {
    index: false,
    follow: true,
  },
};

const effectiveDate = 'August 2, 2026';

const sections = [
  {
    title: 'Scope',
    body: [
      'This Privacy Policy explains how Aernova Inc. collects, uses, discloses, retains, and protects personal information submitted through this website and related business communications.',
      'This website is intended for business, construction, roofing, property, and project inquiries. It is not directed to children.',
    ],
  },
  {
    title: 'Personal Information We Collect',
    body: [
      'When you submit a quote request or contact us, we may collect your name, company, email address, phone number, project description, and any files or details you choose to provide.',
      'We may also receive technical information generated by normal website use, such as browser type, device information, IP address, form security signals, and anti-spam verification results.',
    ],
  },
  {
    title: 'How We Use Personal Information',
    body: [
      'We use personal information to respond to inquiries, prepare project scopes and proposals, schedule calls or site discussions, provide requested services, maintain business records, protect the website from spam or abuse, and comply with legal obligations.',
      'We do not sell personal information.',
    ],
  },
  {
    title: 'Consent',
    body: [
      'By submitting a form, emailing us, or calling us, you consent to Aernova Inc. using the information you provide for the purposes described in this policy.',
      'You may withdraw consent for future communications, subject to legal, contractual, and reasonable business record-keeping requirements.',
    ],
  },
  {
    title: 'Service Providers and Disclosure',
    body: [
      'We may share personal information with service providers that help operate this website, process form submissions, prevent spam, host systems, or support business communications. These providers may include Web3Forms and hCaptcha.',
      "Some service providers may process or store information outside Canada. When information is processed in another jurisdiction, it may be subject to that jurisdiction's laws.",
      'We may also disclose information if required by law, to protect our rights, to prevent fraud or abuse, or as part of a business transaction involving Aernova Inc.',
    ],
  },
  {
    title: 'Retention',
    body: [
      'We retain personal information only as long as reasonably necessary for the purposes described in this policy, including responding to inquiries, managing client relationships, maintaining records, resolving disputes, and meeting legal or accounting obligations.',
      'When information is no longer required, we take reasonable steps to delete, anonymize, or securely dispose of it.',
    ],
  },
  {
    title: 'Safeguards',
    body: [
      'We use reasonable administrative, technical, and organizational safeguards appropriate to the sensitivity of the information. No website, email system, or online service can be guaranteed to be completely secure.',
      'If you need to share sensitive project, site, legal, insurance, or personal information, contact us first so we can discuss an appropriate transfer method.',
    ],
  },
  {
    title: 'Access, Correction, and Questions',
    body: [
      'You may request access to personal information we hold about you, ask that inaccurate information be corrected, or ask questions about our privacy practices by contacting sales@aernova.ca.',
      'We may need to verify your identity before responding to an access or correction request.',
    ],
  },
  {
    title: 'Complaints',
    body: [
      'If you have a privacy concern, please contact us first so we can review and respond. You may also contact the Office of the Privacy Commissioner of Canada if you believe your concern has not been resolved.',
    ],
  },
  {
    title: 'Changes to This Policy',
    body: [
      'We may update this Privacy Policy from time to time. The updated version will be posted on this page with a new effective date.',
    ],
  },
];

export default function PrivacyPage() {
  return <LegalPage eyebrow="Privacy Policy" title="Privacy Policy" sections={sections} />;
}

function LegalPage({
  eyebrow,
  title,
  sections,
}: {
  eyebrow: string;
  title: string;
  sections: { title: string; body: string[] }[];
}) {
  return (
    <main id="main" className="min-h-screen px-8 py-24 lg:px-16">
      <a href="/" className="font-mono-dm text-[0.65rem] tracking-widest uppercase text-cyan">
        Back to Aernova
      </a>
      <div className="max-w-3xl mt-14">
        <span className="font-mono-dm text-[0.65rem] tracking-[0.25em] uppercase text-cyan block mb-4">
          {eyebrow}
        </span>
        <h1 className="font-display text-[clamp(3rem,7vw,6rem)] text-snow tracking-wide leading-none mb-4">
          {title.toUpperCase()}
        </h1>
        <p className="font-mono-dm text-[0.65rem] tracking-widest uppercase text-smoke mb-10">
          Effective {effectiveDate}
        </p>
        <div className="space-y-8">
          {sections.map((section) => (
            <section key={section.title} className="border-t border-edge pt-6">
              <h2 className="font-display text-3xl text-snow tracking-wide mb-3">
                {section.title.toUpperCase()}
              </h2>
              <div className="space-y-3">
                {section.body.map((paragraph) => (
                  <p key={paragraph} className="font-body font-light text-frost/72 leading-relaxed">
                    {paragraph}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}
